import XCTest
@testable import HighlightEngine

/// PARITY: the Swift `FeedbackReplay` must produce byte-for-byte the same per-config stats as the
/// Python harness (`experiments/feedback-replay/replay.py`) on the SAME input. The fixture
/// `Fixtures/synthetic-feedback.jsonl` is generated by that harness's `synth_feedback.generate(Random(42))`
/// (277 events); the golden numbers below are `replay.py`'s output on it. If the two ever diverge, the
/// on-device re-weighting would no longer match the offline analysis — this test is the guard.
final class FeedbackReplayParityTests: XCTestCase {

    /// Decode the harness fixture into the engine's own `HighlightFeedbackEvent` (its Codable tolerates
    /// the omitted-nil optionals Swift's encoder produces — the same shape the device writes).
    private func loadFixtureEvents() throws -> [HighlightFeedbackEvent] {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "synthetic-feedback",
                                                  withExtension: "jsonl"),
                                "synthetic-feedback.jsonl missing from test bundle")
        let text = try String(contentsOf: url, encoding: .utf8)
        let decoder = JSONDecoder()
        return text.split(separator: "\n").compactMap {
            try? decoder.decode(HighlightFeedbackEvent.self, from: Data($0.utf8))
        }
    }

    func testFixtureDecodesFully() throws {
        let events = try loadFixtureEvents()
        XCTAssertEqual(events.count, 277, "every fixture line must decode (parity input must match Python)")
    }

    func testReplayStatsMatchPythonGolden() throws {
        let stats = FeedbackReplay.replay(try loadFixtureEvents())
        XCTAssertEqual(stats.count, 2)

        // Golden from `python3 run.py` on the seeded synthetic data (replay.py).
        let a = try XCTUnwrap(stats["HRHighlightSelector | sm9_lag6_l60_s40_g20"])
        XCTAssertEqual(a.shown, 45)
        XCTAssertEqual(a.kept, 34)
        XCTAssertEqual(a.removed, 11)
        XCTAssertEqual(a.pinned, 10)
        XCTAssertEqual(a.exported, 34)
        XCTAssertEqual(a.regenerated, 1)
        XCTAssertEqual(a.endorsedHigh, 30)
        XCTAssertEqual(a.endorsedTotal, 44)
        XCTAssertEqual(a.effortMix, 0.681818, accuracy: 1e-6)
        XCTAssertEqual(a.satisfaction, 0.877778, accuracy: 1e-6)

        let b = try XCTUnwrap(stats["HRHighlightSelector | sm13_lag6_l70_s30_g25"])
        XCTAssertEqual(b.shown, 52)
        XCTAssertEqual(b.kept, 28)
        XCTAssertEqual(b.removed, 24)
        XCTAssertEqual(b.pinned, 8)
        XCTAssertEqual(b.exported, 28)
        XCTAssertEqual(b.regenerated, 2)
        XCTAssertEqual(b.endorsedHigh, 13)
        XCTAssertEqual(b.endorsedTotal, 36)
        XCTAssertEqual(b.effortMix, 0.361111, accuracy: 1e-6)
        XCTAssertEqual(b.satisfaction, 0.442308, accuracy: 1e-6)
    }

    func testRankingAndRecommendationMatchPython() throws {
        let stats = FeedbackReplay.replay(try loadFixtureEvents())
        let ranked = FeedbackReplay.ranked(stats)
        XCTAssertEqual(ranked.first?.key, "HRHighlightSelector | sm9_lag6_l60_s40_g20")

        // Mirrors run.py's recommendation text for this dataset (effort_mix 0.68 ≥ 0.6 → HR-heavy).
        let rec = FeedbackReplay.recommend(stats)
        XCTAssertTrue(rec.contains("Best config so far: **HRHighlightSelector | sm9_lag6_l60_s40_g20** (satisfaction 0.88)."), rec)
        XCTAssertTrue(rec.contains("effort_mix ≈ 0.68 → users endorse mostly EFFORT moments"), rec)
    }

    // MARK: - Re-weighting (the data-driven path; weights change ONLY from replayed feedback)

    func testTunedWeightingDerivesFromEffortMix() throws {
        let stats = FeedbackReplay.replay(try loadFixtureEvents())
        let tuned = try XCTUnwrap(FeedbackReplay.tunedWeighting(from: stats))
        // Best config effort_mix 0.6818 → HR weight tracks it (clamped ≤ 0.8), scene gets the rest.
        XCTAssertEqual(tuned.hrWeight, 0.681818, accuracy: 1e-6)
        XCTAssertEqual(tuned.sceneWeight, 1 - 0.681818, accuracy: 1e-6)
        XCTAssertEqual(tuned.hrWeight + tuned.sceneWeight, 1.0, accuracy: 1e-9)
    }

    func testNoWeightChangeWithoutEnoughEndorsedData() {
        // The invariant: with no/too-little replayed feedback, weights DON'T change (nil → keep defaults).
        XCTAssertNil(FeedbackReplay.tunedWeighting(from: [:]))
        let thin = FeedbackReplay.replay([
            .init(workoutId: "w", activity: .dance, action: .pinned, atOffset: 1, score: 0.5,
                  highlightKind: .high, selectorName: "S", configFingerprint: "fp", timestamp: 1)
        ])
        XCTAssertNil(FeedbackReplay.tunedWeighting(from: thin), "1 endorsement < minEndorsed ⇒ no change")
    }

    func testWeightsNeverCollapseToSingleSignal() throws {
        // Even an all-effort or all-scene history keeps both signals in the blend (clamp to [0.2, 0.8]).
        func endorsements(high: Bool, n: Int) -> [HighlightFeedbackEvent] {
            (0..<n).map { _ in
                .init(workoutId: "w", activity: .dance, action: .exported, atOffset: 1, score: 0.5,
                      highlightKind: high ? .high : .low, selectorName: "S", configFingerprint: "fp", timestamp: 1)
            }
        }
        let allEffort = try XCTUnwrap(FeedbackReplay.tunedWeighting(from: FeedbackReplay.replay(endorsements(high: true, n: 10))))
        XCTAssertEqual(allEffort.hrWeight, 0.8, accuracy: 1e-9)
        XCTAssertEqual(allEffort.sceneWeight, 0.2, accuracy: 1e-9)
        let allScene = try XCTUnwrap(FeedbackReplay.tunedWeighting(from: FeedbackReplay.replay(endorsements(high: false, n: 10))))
        XCTAssertEqual(allScene.hrWeight, 0.2, accuracy: 1e-9)
        XCTAssertEqual(allScene.sceneWeight, 0.8, accuracy: 1e-9)
    }
}
