import Foundation
import SwiftData

// Wardrobe persistence (wardrobe prompt 01). Three flat tables, plain-UUID FKs like the
// rest of the suite (no SwiftData relationships).
//
// **CloudKit-compatible by construction** (the locked decision): every stored property
// has an inline default or is Optional, there are NO `@Attribute(.unique)` constraints,
// and the item photo is `@Attribute(.externalStorage)` Data — so flipping the container
// to CloudKit mirroring later is a config change, not a migration. Until then the same
// shape rides the suite-level `SnappetBackup` (rows added there in the same change; the
// coverage tripwire test enforces it).

/// One piece of clothing. Enum-backed fields store RAW strings (the suite's
/// raws-stay-raw rule) with typed accessors that fall back safely.
@Model
final class WardrobeItem {
    var id: UUID = UUID()
    var name: String = ""
    var categoryRaw: String = "top"
    var colorRaw: String = "grey"
    var patternRaw: String = "solid"
    var styleRaw: String = "casual"
    var material: String = ""
    /// Who made it (wardrobe prompt 05). Its own field because the real closet was using
    /// `material` for this — Uniqlo 32, Lululemon 30, Temu 10, with 41 of 95 values carrying
    /// stray whitespace so `'Uniqlo '` and `'Uniqlo'` were two brands.
    var brand: String = ""
    /// Free text ("S", "M", "32x30", "EU 42") — sizing has no universal scale worth modelling.
    /// Named `sizeLabel`, not `size`, so it can't be mistaken for a geometry property.
    var sizeLabel: String = ""
    /// Where it was bought. Unlocks the on-demand price check; empty = no check offered.
    var productURL: String = ""
    /// Last fetched price, and WHEN — the timestamp is not optional decoration. Without it a
    /// months-old number reads as live.
    var currentPrice: Double? = nil
    var currentPriceCheckedAt: Date? = nil
    /// The built-in each *custom* enum value behaves like, for scoring (wardrobe prompt 05).
    /// Empty when the raw is already a built-in. Stored ON the item rather than looked up in
    /// `WardrobeVocabulary` so `OutfitComposer` stays a pure function of the item — scoring must
    /// never need a fetch.
    var categoryMapRaw: String = ""
    var colorMapRaw: String = ""
    var patternMapRaw: String = ""
    var styleMapRaw: String = ""
    /// Raw season ids; empty = all-season.
    var seasonsRaw: [String] = []
    /// Purchase cost — powers cost-per-wear; optional on purpose.
    var cost: Double? = nil
    var isFavorite: Bool = false
    var isArchived: Bool = false
    var notes: String = ""
    var createdAt: Date = Date()
    /// The cut-out (or original) photo, capped at `WardrobeImagePolicy.displayMaxEdge`.
    /// External storage keeps the row light and the bytes CloudKit-syncable later;
    /// nil = category-emoji placeholder tile. Only the detail hero reads this — every
    /// grid tile reads `thumbnailData`.
    @Attribute(.externalStorage) var imageData: Data? = nil
    /// Grid thumbnail (`WardrobeImagePolicy.thumbnailMaxEdge`), derived from `imageData`.
    ///
    /// Deliberately NOT `.externalStorage`: the whole point is that the closet grid's bytes
    /// ride the row fetch instead of costing one file read per tile. At ≤320px this is tens
    /// of KB, so a 100-item closet adds only a few MB to the fetch.
    ///
    /// Derived data, so it is deliberately absent from `SnappetBackup` (the backup already
    /// carries the masters) and regenerated by `WardrobeImageMigration` after a restore.
    var thumbnailData: Data? = nil
    /// What the COVER photo shows (wardrobe prompt 04). Lives here because the cover itself lives
    /// here rather than in a `WardrobePhoto` row. Defaults to `front`, which is what every
    /// pre-prompt-04 garment's single photo is — so existing rows read correctly with no migration.
    var coverPhotoRoleRaw: String = "front"

    init(id: UUID = UUID(), name: String, category: GarmentCategory,
         color: GarmentColorFamily, pattern: GarmentPattern = .solid,
         style: GarmentStyle = .casual, material: String = "",
         seasons: Set<GarmentSeason> = [], cost: Double? = nil,
         isFavorite: Bool = false, isArchived: Bool = false,
         notes: String = "", createdAt: Date = .now, imageData: Data? = nil,
         thumbnailData: Data? = nil) {
        self.id = id
        self.name = name
        self.categoryRaw = category.rawValue
        self.colorRaw = color.rawValue
        self.patternRaw = pattern.rawValue
        self.styleRaw = style.rawValue
        self.material = material
        self.seasonsRaw = seasons.map(\.rawValue).sorted()
        self.cost = cost
        self.isFavorite = isFavorite
        self.isArchived = isArchived
        self.notes = notes
        self.createdAt = createdAt
        self.imageData = imageData
        self.thumbnailData = thumbnailData
    }

    // Typed accessors. Each prefers the stored raw, then the custom value's "behaves like" map,
    // then the safe default (wardrobe prompt 05). The map fallback is what keeps an item with a
    // custom color ("Mustard" → yellow) inside `OutfitComposer`'s harmony maths instead of
    // silently dropping out of every suggestion. Setting always writes a built-in and CLEARS the
    // map, so a value can never be both.
    var category: GarmentCategory {
        get { GarmentCategory(rawValue: categoryRaw)
                ?? GarmentCategory(rawValue: categoryMapRaw) ?? .top }
        set { categoryRaw = newValue.rawValue; categoryMapRaw = "" }
    }
    var color: GarmentColorFamily {
        get { GarmentColorFamily(rawValue: colorRaw)
                ?? GarmentColorFamily(rawValue: colorMapRaw) ?? .grey }
        set { colorRaw = newValue.rawValue; colorMapRaw = "" }
    }
    var pattern: GarmentPattern {
        get { GarmentPattern(rawValue: patternRaw)
                ?? GarmentPattern(rawValue: patternMapRaw) ?? .solid }
        set { patternRaw = newValue.rawValue; patternMapRaw = "" }
    }
    var style: GarmentStyle {
        get { GarmentStyle(rawValue: styleRaw)
                ?? GarmentStyle(rawValue: styleMapRaw) ?? .casual }
        set { styleRaw = newValue.rawValue; styleMapRaw = "" }
    }

    /// What the UI shows for an enum field: the user's own wording when it's custom
    /// ("Mustard"), the built-in's title otherwise ("Yellow").
    var colorDisplay: String {
        GarmentColorFamily(rawValue: colorRaw)?.title ?? colorRaw
    }
    var categoryDisplay: String {
        GarmentCategory(rawValue: categoryRaw)?.title ?? categoryRaw
    }
    var patternDisplay: String {
        GarmentPattern(rawValue: patternRaw)?.title ?? patternRaw
    }
    var styleDisplay: String {
        GarmentStyle(rawValue: styleRaw)?.title ?? styleRaw
    }

    /// Price movement since purchase, when both numbers are known. Negative = cheaper now.
    var priceDeltaFraction: Double? {
        guard let cost, cost > 0, let currentPrice else { return nil }
        return (currentPrice - cost) / cost
    }
    var seasons: Set<GarmentSeason> {
        get { Set(seasonsRaw.compactMap(GarmentSeason.init(rawValue:))) }
        set { seasonsRaw = newValue.map(\.rawValue).sorted() }
    }
    var coverPhotoRole: GarmentPhotoRole {
        get { GarmentPhotoRole(rawValue: coverPhotoRoleRaw) ?? .front }
        set { coverPhotoRoleRaw = newValue.rawValue }
    }

    /// Pure mirror for the composer/coach. Wear history is joined in by the caller
    /// (views own the `WearEvent` query; tests pass literals).
    func profile(wearCount: Int = 0, lastWornAt: Date? = nil) -> GarmentProfile {
        GarmentProfile(id: id, name: name, category: category, color: color,
                       pattern: pattern, style: style, seasons: seasons,
                       isFavorite: isFavorite, wearCount: wearCount, lastWornAt: lastWornAt)
    }
}

/// One EXTRA photo of a garment (wardrobe prompt 04) — front / back / worn / tag / detail.
///
/// The **cover** photo is deliberately NOT a row here: it stays on `WardrobeItem.imageData` /
/// `thumbnailData`. Two reasons, both load-bearing. The closet grid renders 100 tiles and must never
/// join a second table to do it (prompt 03 exists because that grid was the hang), and keeping the
/// cover in place meant prompt 04 shipped with **zero migration** — every pre-existing garment is
/// already a valid one-photo item with no rows here at all.
///
/// Same conventions as the rest of the module: plain UUID FK (no SwiftData relationship), raws stay
/// raw, inline defaults everywhere so the container can be flipped to CloudKit later.
@Model
final class WardrobePhoto {
    var id: UUID = UUID()
    /// FK to `WardrobeItem.id`. Optional for CloudKit-compatibility, not because it's meaningful —
    /// an orphan row is a bug. There is no cascade on a plain UUID FK, so item deletion must sweep
    /// these explicitly (`WardrobePhotoStore.deleteAll(forItem:)`).
    var itemID: UUID? = nil
    var roleRaw: String = "detail"
    /// Display order among the extras; the cover always sorts first and isn't in this table.
    var sortIndex: Int = 0
    /// Capped at `WardrobeImagePolicy.displayMaxEdge` by `WardrobeImageStore`, like the cover.
    @Attribute(.externalStorage) var imageData: Data? = nil
    /// Inline, NOT `.externalStorage` — same reasoning as `WardrobeItem.thumbnailData` (prompt 03):
    /// a `.count` read must not become a main-thread file read.
    var thumbnailData: Data? = nil
    var createdAt: Date = Date()

    init(id: UUID = UUID(), itemID: UUID?, role: GarmentPhotoRole, sortIndex: Int = 0,
         imageData: Data? = nil, thumbnailData: Data? = nil, createdAt: Date = .now) {
        self.id = id
        self.itemID = itemID
        self.roleRaw = role.rawValue
        self.sortIndex = sortIndex
        self.imageData = imageData
        self.thumbnailData = thumbnailData
        self.createdAt = createdAt
    }

    var role: GarmentPhotoRole {
        get { GarmentPhotoRole(rawValue: roleRaw) ?? .detail }
        set { roleRaw = newValue.rawValue }
    }
}

/// One remembered custom dropdown value (wardrobe prompt 05) — "add a custom value in all the
/// fields which have dropdown and also update same value in related dropdown for future".
///
/// `mapsToRaw` is the built-in a *scored* field's custom value behaves like (a custom "Mustard"
/// maps to `yellow`); empty for the unscored free-text fields (brand / size / material), which have
/// nothing to score against.
@Model
final class WardrobeVocabulary {
    var id: UUID = UUID()
    /// Which dropdown this belongs to — `WardrobeVocabularyRules.Field` raw value.
    var fieldRaw: String = "brand"
    /// The value as the user typed it, already normalized (trimmed, inner whitespace collapsed).
    var value: String = ""
    /// Nearest built-in for scoring; empty for unscored fields.
    var mapsToRaw: String = ""
    /// Drives most-used-first ordering, so the second Uniqlo item is one tap.
    var useCount: Int = 0
    var createdAt: Date = Date()

    init(id: UUID = UUID(), field: WardrobeVocabularyRules.Field, value: String,
         mapsToRaw: String = "", useCount: Int = 1, createdAt: Date = .now) {
        self.id = id
        self.fieldRaw = field.rawValue
        self.value = value
        self.mapsToRaw = mapsToRaw
        self.useCount = useCount
        self.createdAt = createdAt
    }

    var field: WardrobeVocabularyRules.Field {
        get { WardrobeVocabularyRules.Field(rawValue: fieldRaw) ?? .brand }
        set { fieldRaw = newValue.rawValue }
    }
}

/// One field rewritten by the tidy-up (wardrobe prompt 05) — the undo log.
///
/// The cleanup touches ~105 values across a real closet, so it is recorded rather than trusted:
/// every edit in one run shares a `batchID`, and restoring `oldValue` for that batch is the whole
/// of "Undo tidy up". Append-only; a run that is undone marks its rows rather than deleting them,
/// so the history of what happened survives.
@Model
final class WardrobeTidyEdit {
    var id: UUID = UUID()
    var batchID: UUID = UUID()
    var itemID: UUID? = nil
    /// Which property was rewritten — `WardrobeTidyPlan.Field` raw value.
    var fieldRaw: String = "brand"
    var oldValue: String = ""
    var newValue: String = ""
    var appliedAt: Date = Date()
    var isUndone: Bool = false

    init(id: UUID = UUID(), batchID: UUID, itemID: UUID?, fieldRaw: String,
         oldValue: String, newValue: String, appliedAt: Date = .now, isUndone: Bool = false) {
        self.id = id
        self.batchID = batchID
        self.itemID = itemID
        self.fieldRaw = fieldRaw
        self.oldValue = oldValue
        self.newValue = newValue
        self.appliedAt = appliedAt
        self.isUndone = isUndone
    }
}

/// One wear of one item (a worn outfit writes one event per piece). Append-only.
@Model
final class WearEvent {
    var id: UUID = UUID()
    var itemID: UUID? = nil
    /// Set when the wear came from wearing a whole outfit.
    var outfitID: UUID? = nil
    var wornOn: Date = Date()

    init(id: UUID = UUID(), itemID: UUID?, outfitID: UUID? = nil, wornOn: Date = .now) {
        self.id = id
        self.itemID = itemID
        self.outfitID = outfitID
        self.wornOn = wornOn
    }
}

/// A saved/worn outfit: parallel `itemIDs`/`slotRolesRaw` arrays preserve board order.
@Model
final class WardrobeOutfit {
    var id: UUID = UUID()
    var title: String = ""
    var occasionRaw: String = "casualWeekend"
    var tempBandRaw: String = "mild"
    var seasonRaw: String = "spring"
    /// The composer's "why this works" lines, newline-joined.
    var rationale: String = ""
    var itemIDs: [UUID] = []
    var slotRolesRaw: [String] = []
    var isFavorite: Bool = false
    var createdAt: Date = Date()
    var lastWornAt: Date? = nil
    /// "forYou" | "custom" — which surface composed it.
    var sourceRaw: String = "custom"

    init(id: UUID = UUID(), title: String, occasion: OutfitOccasion,
         tempBand: TempBand, season: GarmentSeason, rationale: [String],
         slots: [ComposedOutfit.Slot], isFavorite: Bool = false,
         createdAt: Date = .now, lastWornAt: Date? = nil, sourceRaw: String = "custom") {
        self.id = id
        self.title = title
        self.occasionRaw = occasion.rawValue
        self.tempBandRaw = tempBand.rawValue
        self.seasonRaw = season.rawValue
        self.rationale = rationale.joined(separator: "\n")
        self.itemIDs = slots.map(\.itemID)
        self.slotRolesRaw = slots.map(\.role.rawValue)
        self.isFavorite = isFavorite
        self.createdAt = createdAt
        self.lastWornAt = lastWornAt
        self.sourceRaw = sourceRaw
    }

    var occasion: OutfitOccasion {
        get { OutfitOccasion(rawValue: occasionRaw) ?? .casualWeekend }
        set { occasionRaw = newValue.rawValue }
    }
    var rationaleLines: [String] {
        rationale.isEmpty ? [] : rationale.components(separatedBy: "\n")
    }
    /// Rebuild the composed value (for re-rendering the board / wear-again).
    var composed: ComposedOutfit {
        let slots = zip(itemIDs, slotRolesRaw).map { id, raw in
            ComposedOutfit.Slot(role: GarmentCategory(rawValue: raw) ?? .top, itemID: id)
        }
        return ComposedOutfit(slots: slots, rationale: rationaleLines, score: 0)
    }
}
