package com.snappet.mobile.feature.kilter

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Entity
import androidx.room.Index
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/** How a logged attempt resolved. Stored by [name] on [KilterLogEntry]. Mirrors iOS `KilterAscentStatus`. */
enum class KilterAscentStatus(val label: String) {
    FLASH("Flash"), SENT("Sent"), PROJECT("Project"), ATTEMPT("Attempt");

    /** Counts toward "sends" in the history pyramid. */
    val isSend: Boolean get() = this == SENT || this == FLASH

    companion object {
        fun from(raw: String): KilterAscentStatus = entries.firstOrNull { it.name == raw } ?: ATTEMPT
    }
}

/**
 * One logged attempt on a climb at a given angle. Persisted in the shared SnappetCore store (separate
 * from the read-only catalog). Snapshots `climbName`/`gradeLabel` so History renders without
 * re-opening the catalog. Optionally tagged with the `sessionId` of the board session it was logged
 * in. Mirrors the iOS `KilterLogEntry` `@Model`.
 */
@Entity(tableName = "kilter_log")
data class KilterLogEntry(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val climbUuid: String,
    val climbName: String,
    val angle: Int,
    /** Float difficulty at the logged angle (for the grade pyramid / sorting). */
    val difficulty: Double,
    val gradeLabel: String,
    /** [KilterAscentStatus.name]. */
    val status: String,
    val attempts: Int = 1,
    /** Epoch millis; newest-first sorting. */
    val createdAt: Long,
    /** [KilterSession.id] when captured during a connected board session; null for ad-hoc logs. */
    val sessionId: String? = null,
)

/**
 * A board session — opened when a board connects over BLE (or started manually), grouping the
 * [KilterLogEntry]s logged while active so History can show sessions. Mirrors iOS `KilterSession`.
 */
@Entity(tableName = "kilter_session")
data class KilterSession(
    @PrimaryKey val id: String,
    val startedAt: Long,
    val endedAt: Long? = null,
    val angle: Int,
    /** `"ble"` when auto-captured from a connected board, `"manual"` otherwise. */
    val source: String,
    // ── HR enrichment (issue #92, schema v4→v5). All NULLABLE so the bump is a pure additive
    //    AutoMigration (no SQL, no data touched). Populated when a BLE heart-rate strap is captured
    //    during the session; null for sessions logged without a strap or before this version.
    //    NOTE FOR REVIEWER: Wave 2 also bumps to v5 (workout columns) in a separate worktree — at
    //    merge time renumber ONE migration to v5→v6. This column-set is self-contained.
    /** Average bpm over the session, when an HR strap was captured. */
    val avgHr: Int? = null,
    /** Peak bpm over the session, when an HR strap was captured. */
    val maxHr: Int? = null,
    /** Number of HR samples captured (0/null when no strap). */
    val hrSampleCount: Int? = null,
    // ── P4 history metadata (schema v6→v7). All NULLABLE so the bump is a pure additive
    //    AutoMigration (no SQL, no data touched). Mirrors iOS `KilterSession.title/notes/layoutId`.
    /** A user-given name for the session (e.g. "Comp prep"); null → History falls back to a date label. */
    val title: String? = null,
    /** A free-form note about the whole session (how it felt, conditions, goals); null for existing rows. */
    val notes: String? = null,
    /** The board layout this session ran on ([KilterLayout.id]), so History can facet by board; null if unknown. */
    val layoutId: Int? = null,
)

/** A climb the user starred. Its own table so the "Saved" filter is a fast membership check. */
@Entity(tableName = "kilter_favorite")
data class KilterFavorite(
    @PrimaryKey val climbUuid: String,
    val addedAt: Long,
)

/**
 * A climb the user **lit on the board** (Kilter Improvement P5) — the brand-new axis the app couldn't show
 * before: every climb pulled up and worked, including the ones never formally logged as an ascent. Snapshots
 * the climb's display facts (name/grade/angle/layout/size) so "On the Board" renders a row without re-opening
 * the catalog. **Deduped per climb-per-session** at CAPTURE time (the [KilterDao] upsert), mirroring the iOS
 * dedup intent: re-lighting a project ten times in one session yields ONE row (the `litAt` bumps to the latest
 * light). Status (Lit / Attempt / Sent) is joined from [KilterLogEntry] by the pure [KilterOnTheBoard] helper,
 * never stored here. Bridges to [KilterOnTheBoard.LitEvent] via [asLitEvent]. Mirrors iOS `KilterLitEvent`.
 * Additive table → a pure v6→v7 AutoMigration.
 *
 * Identity: an autogenerated [id] (a row's surrogate key), with a UNIQUE INDEX on `(climbUuid, sessionId)` so
 * the upsert can collapse re-lights to one row per climb-per-session (the dedup key the engine uses).
 */
@Entity(
    tableName = "kilter_lit_event",
    indices = [Index(value = ["climbUuid", "sessionId"], unique = true)],
)
data class KilterLitEvent(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val climbUuid: String,
    val climbName: String,
    val gradeLabel: String,
    val angle: Int,
    val layoutId: Int? = null,
    val sizeId: Int? = null,
    /** Epoch millis — when the climb was most-recently lit in this session (bumped on each re-light). */
    val litAt: Long,
    /** Whether a board was actually connected when lit (an on-screen render with no board still records intent). */
    val wasConnected: Boolean = false,
    /** [KilterSession.id] when lit during a session; null for out-of-session lights (its own dedup bucket). */
    val sessionId: String? = null,
) {
    /** Adapt to the pure-engine value type so the [KilterOnTheBoard] logic never touches a Room entity. */
    fun asLitEvent(): KilterOnTheBoard.LitEvent = KilterOnTheBoard.LitEvent(
        climbUuid = climbUuid, climbName = climbName, gradeLabel = gradeLabel, angle = angle,
        layoutId = layoutId ?: 0, sizeId = sizeId ?: 0, litAt = litAt,
        wasConnected = wasConnected, sessionId = sessionId,
    )
}

/**
 * A climb the user authored on this device — manually (hold-by-hold) or via the on-device generator.
 * Keyed by the deterministic content uuid ([KilterClimbIdentity]) so the same climb authored twice (even
 * on another device) collapses to one row. [asClimb] adapts it to the read-only [KilterClimb] so it flows
 * through the normal render / detail / BLE / logging path. Mirrors iOS `KilterCreatedClimb`. Surfaced via
 * the browse list's "Mine" filter.
 */
@Entity(tableName = "kilter_created")
data class KilterCreatedClimb(
    @PrimaryKey val uuid: String,
    val name: String,
    /** The author's display name (the [KilterClimb.setter] for this climb). */
    val setterUsername: String,
    val layoutId: Int,
    /** The `product_size_id` the climb was authored against (the board it fits + its LED basis). */
    val sizeId: Int,
    /** The angle the user designed for (created climbs have no per-angle catalog stats). */
    val angle: Int,
    /** `p<placement>r<role>` hold encoding (canonical/sorted). */
    val frames: String,
    val edgeLeft: Int,
    val edgeRight: Int,
    val edgeBottom: Int,
    val edgeTop: Int,
    val isNoMatch: Boolean = false,
    /** The generator's predicted grade, or the user's pick; null when unknown. */
    val predictedGrade: Double? = null,
    /** `"manual"` or `"generated"`. */
    val source: String = "manual",
    /** The generator model id when generated (provenance), else null. */
    val modelId: String? = null,
    val createdAt: Long,
) {
    /** Adapt to the read-only catalog value type so created climbs reuse the whole render/detail/BLE path. */
    fun asClimb(): KilterClimb = KilterClimb(
        uuid = uuid, name = name, setter = setterUsername, layoutId = layoutId,
        edgeLeft = edgeLeft, edgeRight = edgeRight, edgeBottom = edgeBottom, edgeTop = edgeTop,
        frames = frames, description = "", isNoMatch = isNoMatch,
    )
}

/**
 * A **persisted planned session** — a [KilterRecommender.Plan] snapshotted on Start, with per-pick
 * completion that survives any recommender re-run. Decoupling the plan from the live recommender is what
 * fixes the "completed send/project pick vanishes" defect and gives the run a re-enterable home.
 * [sessionId] pins it to its [KilterSession] once started (and freezes it); done-state is read from each
 * item's status, never re-derived. Items ride as a JSON column ([itemsJson], via [KilterPlanItemsCodec])
 * — there is no Room `@TypeConverter` in this codebase. Mirrors iOS `KilterPlan`. Additive table → a
 * pure v5→v6 AutoMigration.
 */
@Entity(tableName = "kilter_plan")
data class KilterPlanEntity(
    @PrimaryKey val id: String,
    val createdAt: Long,
    val angle: Int,
    val layoutId: Int,
    val workingDifficulty: Double? = null,
    val workingGradeLabel: String? = null,
    val title: String? = null,
    /** [KilterSession.id] once Started — pins + freezes the plan; null while in Plan-ready. */
    val sessionId: String? = null,
    /** Set by Finish (or recover auto-close); null while in progress. */
    val completedAt: Long? = null,
    // Options snapshot (the strategy the plan was generated with; mirrors KilterRecommender.Options).
    val optionsTargetCount: Int = 6,
    val optionsSendThreshold: Int = 2,
    val optionsPreferUnsent: Boolean = true,
    val optionsGradeOffset: Int = 0,
    val strategyRaw: String? = null,
    /** Ordered picks with per-item status, JSON-encoded (kotlinx.serialization). */
    val itemsJson: String = "[]",
)

@Dao
interface KilterDao {
    @Insert suspend fun insertLog(entry: KilterLogEntry)

    @Query("SELECT * FROM kilter_log ORDER BY createdAt DESC")
    fun logsFlow(): Flow<List<KilterLogEntry>>

    /** Issue #88: a fat-fingered Flash is correctable — single-row delete + status fix. */
    @Delete suspend fun deleteLog(entry: KilterLogEntry)

    @Query("UPDATE kilter_log SET status = :status WHERE id = :id")
    suspend fun updateLogStatus(id: Long, status: String)

    @Query("DELETE FROM kilter_log") suspend fun clearLogs()

    @Insert suspend fun insertSession(session: KilterSession)

    @Query("UPDATE kilter_session SET endedAt = :endedAt WHERE id = :id")
    suspend fun endSession(id: String, endedAt: Long)

    /** Issue #92: persist the captured HR summary onto the session on end (additive v5 columns). */
    @Query("UPDATE kilter_session SET avgHr = :avgHr, maxHr = :maxHr, hrSampleCount = :count WHERE id = :id")
    suspend fun setSessionHr(id: String, avgHr: Int?, maxHr: Int?, count: Int?)

    /** P4: edit a session's metadata (title/notes/angle/layout) from the session detail (additive v7 columns). */
    @Query("UPDATE kilter_session SET title = :title, notes = :notes, angle = :angle, layoutId = :layoutId WHERE id = :id")
    suspend fun updateSessionMetadata(id: String, title: String?, notes: String?, angle: Int, layoutId: Int?)

    @Query("SELECT * FROM kilter_session ORDER BY startedAt DESC")
    fun sessionsFlow(): Flow<List<KilterSession>>

    /** Open (un-ended) sessions, newest first — for the manager's recover-on-entry re-adoption. */
    @Query("SELECT * FROM kilter_session WHERE endedAt IS NULL ORDER BY startedAt DESC")
    suspend fun openSessions(): List<KilterSession>

    @Query("DELETE FROM kilter_session") suspend fun clearSessions()

    // ── Lit-on-the-board events (KilterLitEvent, P5). Dedup is enforced at CAPTURE time, per
    //    climb-per-session, mirroring iOS: [upsertLitEvent] bumps an existing row's litAt/wasConnected
    //    instead of appending a duplicate, keeping the lit log bounded.

    /**
     * Record a climb being lit, deduped per `(climbUuid, sessionId)` (the engine's dedup key). When a row
     * already exists for that climb in that session, bump its `litAt` to the latest light and OR in
     * `wasConnected` (a real on-the-wall light is sticky); otherwise insert a fresh row. Mirrors the iOS
     * dedup-at-capture intent so re-lighting a project many times in one session yields ONE row.
     */
    @androidx.room.Transaction
    suspend fun upsertLitEvent(event: KilterLitEvent) {
        val existing = litEventFor(event.climbUuid, event.sessionId)
        if (existing == null) {
            insertLitEvent(event)
        } else {
            bumpLitEvent(
                id = existing.id,
                litAt = maxOf(existing.litAt, event.litAt),
                wasConnected = existing.wasConnected || event.wasConnected,
            )
        }
    }

    /** The lit-event row for a climb in a session (the dedup bucket), if any. A null session is its own bucket. */
    @Query(
        "SELECT * FROM kilter_lit_event WHERE climbUuid = :climbUuid " +
            "AND (sessionId = :sessionId OR (:sessionId IS NULL AND sessionId IS NULL)) LIMIT 1",
    )
    suspend fun litEventFor(climbUuid: String, sessionId: String?): KilterLitEvent?

    @Insert suspend fun insertLitEvent(event: KilterLitEvent)

    @Query("UPDATE kilter_lit_event SET litAt = :litAt, wasConnected = :wasConnected WHERE id = :id")
    suspend fun bumpLitEvent(id: Long, litAt: Long, wasConnected: Boolean)

    /** All lit events, newest light first — the "On the Board" timeline source. */
    @Query("SELECT * FROM kilter_lit_event ORDER BY litAt DESC")
    fun litEventsFlow(): Flow<List<KilterLitEvent>>

    /** The most-recent N lit events for the Kilter-root "Recently on the board" rail. */
    @Query("SELECT * FROM kilter_lit_event ORDER BY litAt DESC LIMIT :limit")
    fun recentLitEventsFlow(limit: Int): Flow<List<KilterLitEvent>>

    @Query("DELETE FROM kilter_lit_event") suspend fun clearLitEvents()

    @Query("SELECT * FROM kilter_favorite ORDER BY addedAt DESC")
    fun favoritesFlow(): Flow<List<KilterFavorite>>

    @Insert suspend fun addFavorite(favorite: KilterFavorite)
    @Delete suspend fun removeFavorite(favorite: KilterFavorite)

    // Authored climbs (manual editor / generator).
    @androidx.room.Upsert suspend fun upsertCreated(climb: KilterCreatedClimb)

    @Query("SELECT * FROM kilter_created ORDER BY createdAt DESC")
    fun createdFlow(): Flow<List<KilterCreatedClimb>>

    @Query("SELECT * FROM kilter_created")
    suspend fun allCreated(): List<KilterCreatedClimb>

    @Query("SELECT * FROM kilter_created WHERE uuid = :uuid LIMIT 1")
    suspend fun createdByUuid(uuid: String): KilterCreatedClimb?

    // Planned sessions (KilterPlan).
    @androidx.room.Upsert suspend fun upsertPlan(plan: KilterPlanEntity)

    /** The open (un-finished) plan pinned to a session, if any. Mirrors iOS openPlan(forSession:). */
    @Query("SELECT * FROM kilter_plan WHERE sessionId = :sid AND completedAt IS NULL LIMIT 1")
    suspend fun openPlanForSession(sid: String): KilterPlanEntity?

    /** Close (in lockstep with the session ending / recovery auto-close) any open plan for a session. */
    @Query("UPDATE kilter_plan SET completedAt = :completedAt WHERE sessionId = :sid AND completedAt IS NULL")
    suspend fun closePlanForSession(sid: String, completedAt: Long)

    @Query("SELECT * FROM kilter_plan ORDER BY createdAt DESC")
    fun plansFlow(): Flow<List<KilterPlanEntity>>

    @Delete suspend fun deletePlan(plan: KilterPlanEntity)

    @Query("DELETE FROM kilter_plan") suspend fun clearPlans()
}
